### ISSUE TITLE
Dependency conflict with third-party plugins

### ISSUE THREAD

**Issue by Nice3point** [lookup-foundation/RevitLookup#269]
RevitLookup uses third-party dependencies produced by other developers. User plugins may also use these dependencies, but of different versions, which will cause a conflict and an exception on startup. We have no control over this process, and we cannot prevent other developers from using third-party libraries.

Why are you getting this error in RevitLookup and not in another plugin? Because plugins are loaded in alphabetical order, and the 'R' is near the end, so that's where you get the exception and RevitLookup not working. Unfortunately, the plugin that is loaded first forces Revit to use it dependencies for all plugins. And if it's outdated, RevitLookup, which uses the newest one, will simply be incompatible, if everything was in reverse order this could have been avoided.

At the moment there are some ways, disable conflicting plugins:
- Use [Revit 2025](https://github.com/Nice3point/RevitToolkit#add-ins-dependency-isolation), in this version RevitLookup dependencies are isolated from other plugins.
- Update user plugins to the newest version.
- You can try to rename the RevitLookup loading manifest, give it a name like `_RevitLookup.addin`. Add-ins are loaded in alphabetic order.
- Downgrade the RevitLookup version.
- Download the [DependenciesReport](https://github.com/jeremytammik/RevitLookup/issues/269#issuecomment-2323309590) tool and analyse conflicts.
- Download the [AssembliesReport](https://github.com/jeremytammik/RevitLookup/issues/269#issuecomment-2323309590) tool and share you report here.

Remember though, you can fix RevitLookup in this way, but there is a chance that conflicting plugins may not work.

RevitLookup dependencies list:
https://github.com/jeremytammik/RevitLookup/blob/dev/source/RevitLookup/RevitLookup.csproj#L45-L71

**Comment by Nice3point** [comment]
A tool for analysing and updating dependencies. If you have problems with running RevitLookup, please send reports to

[DependenciesReport.zip](https://github.com/user-attachments/files/16818406/DependenciesReport.zip)
Source code: https://github.com/jeremytammik/RevitLookup/tree/dev/source/DependenciesReport

![изображение](https://github.com/user-attachments/assets/a5f94bd8-7eca-4998-91c7-99d7b079fa47)
![изображение](https://github.com/user-attachments/assets/649b6f75-3f55-42b5-8c77-6df4dc04b72d)

**Comment by acco-jpitts** [comment]
The current RevitLookup 2025.08 uses Nice3point.Revit.Toolkit 2025.0.1
My addin was built using your project templates and is using the latest Nice3point.Revit.Toolkit 2025.0.2

![image](https://github.com/user-attachments/assets/cda1b624-791d-409d-a450-846054688ff8)
![image](https://github.com/user-attachments/assets/7b9ac4fe-3828-4e89-a3c1-12aeb9b15f79)

I built RevitLookup using the current Toolkit 2025.0.2 and had no issues loading both. 
![image](https://github.com/user-attachments/assets/c2ab171e-7186-4f96-9233-5a0712ed981d)

Why am I still running into this issue in 2025?

I'm unable to run the DependenciesReport because company hyper-aggressive anti-virus doesn't like it.

**Comment by Nice3point** [comment]
@acco-jpitts at the moment Revit Toolkit is the only one bottleneck that can cause failures in Revit 2025, as it is this library that provides isolation. I will look into how to get around this, thanks for the clarification

**Comment by trgiangv** [comment]
@Nice3point Please have a look, there have conflict between **Python node in Dynamo** and **RevitLookup** (Tested on Revit 2025.0.2, Dynamo 3.2)

![image](https://github.com/user-attachments/assets/2b9b6a40-23ad-48f0-b592-7e085cf96f70)

![2024-10-07_16h37_26](https://github.com/user-attachments/assets/65a3b3b7-2dc5-4387-b438-86976d4c5bf7)

**Comment by Nice3point** [comment]
@trgiangv we already have an issue https://github.com/jeremytammik/RevitLookup/issues/272. Dynamo team hasn't made any comments on this topic, and I have no idea why initial loading of Python node can affect RevitLookup functioning

**Comment by Nice3point** [comment]
Native addins isolation planned for feature Revit update

[Feature Summary - Add-in Dependency Isolation.pdf](https://github.com/user-attachments/files/17757100/Feature.Summary.-.Add-in.Dependency.Isolation.pdf)

**Comment by ricaun** [comment]
> Native add-in isolation planned for feature Revit updates

Interesting! Where did you get this file? 
If is the Revit Preview probably is better to share the link to the Feature inside the Revit Preview Forum, and not the Feature Summary file.

**Comment by ricaun** [comment]
I was experimenting with `ILRepack` and decided to try in `RevitLookUp` to repack all dependencies inside the main `RevitLookup.dll`

In the end only `RevitLookup.dll` and `RevitLookup.UI.dll` is available inside the plugin, and looks every thing is working like should be.

Looks better and easier than the Isolation approach all the dependencies are inside the main `RevitLookup.dll`, so is impossible to have some conflict with other dependencies already loaded inside Revit.

Here is a image inside Revit 2025, with only `RevitLookup.dll` and `RevitLookup.UI.dll` loaded inside Revit, any Nice3Point dependencies is not loaded because is already inside the main dll.

![Image](https://github.com/user-attachments/assets/443ce154-8625-42cf-ab55-0613e2618e05)

I was messing with bundle so here is the version with `ILRepack` I'm using.

[RevitLookup.bundle.zip](https://github.com/user-attachments/files/18444593/RevitLookup.bundle.zip)

And the repo: https://github.com/ricaun/RevitLookup/tree/refs/heads/dev-bundle-ilrepack

I'm using my custom `ricaun.ILRepack` tool to repack the dlls using `Target` in the end of build process.

* [ricaun.ILRepack](https://www.nuget.org/packages/ricaun.ILRepack/1.0.0-rc#readme-body-tab)

Using this code inside the `csproj` to repack all dlls except the `RevitLookup.UI.dll`.

```xml
<ItemGroup>
    <PackageReference Include="ricaun.ILRepack" Version="1.0.0-rc" />
    <ILRepackIgnoreReferences Include="RevitLookup.UI.dll" />
</ItemGroup>

<PropertyGroup>
    <ILRepackImportance>High</ILRepackImportance>
    <ILRepackCommandImportance>High</ILRepackCommandImportance>
    <ILRepackCommandExtra>/union /allowduplicateresources</ILRepackCommandExtra>
</PropertyGroup>
```

This would fix once for all the dependency conflict with third-party plugins, and works with all Revit version.

**Comment by Nice3point** [comment]
I don't really feel like this would make sense in Revit 2026 with a native isolation. What do you think?

**Comment by ricaun** [comment]
> I don't really feel like this would make sense in Revit 2026 with a native isolation. What do you think?

I guess you could not use `ILRepack` in Revit 2026, but I feel Autodesk gonna mess-up the feature native isolation.

**Comment by Nice3point** [comment]
Probably they will release it with insufficient quality, given the strict release policy they will not finish the edits with the manifest, and we will need to look for workarounds. Just in case we can use the repack, for now let's wait for April and new news

**Comment by Nice3point** [comment]
So, Il-Repack is not compatible with the current code base.

Blocked by: https://github.com/gluck/il-repack/issues/387

**Comment by ricaun** [comment]
> So, Il-Repack is not compatible with the current code base.
> 
> Blocked by: [gluck/il-repack#387](https://github.com/gluck/il-repack/issues/387)

You don't need to repack the UI, because you already copy the whole project and rebuild with a different assembly name. 

I don't know exactly how the new code base is working but only the references that is not start with RevitLookup should be repacked.

**Comment by Nice3point** [comment]
This will not work, now RevitLookup consists of more than one file. Also RevitLookup.Ui.Framework contains WPF markup, which will not allow to merge dlls so easily because of the issue above @ricaun

**Comment by ricaun** [comment]
Interesting a lot of projects, maybe the way would be to have another project just to repack the references, like `RevitLookup.Extensions` with `Microsoft.Extensions.*` and `Serilog.*` and use that project as reference in the others that requires `Microsoft.Extensions.*` or `Serilog.*`.

**Comment by Nice3point** [comment]
A separate project is a bad way to go, the current implementation should not depend on whether Repack is used or not. Still it is an additional option, and besides we will not use it for Revit 2026+ in favor of Revit built-in AssemblyLoadContext

**Comment by ricaun** [comment]
> A separate project is a bad way to go, the current implementation should not depend on whether Repack is used or not. Still it is an additional option, and besides we will not use it for Revit 2026+ in favor of Revit built-in AssemblyLoadContext. So, if you dynamically link to the project after the repack, maybe it will be fine, but it's a very complex approach, you can try.
> 
> I think it's best to wait for the Il-Repack patch, as it will solve the current problem completely. The whole problem is that the Package URL doesn't updated in the Ui.Framework, but we cannot exclude it from the repack, because it refers to CommunityToolkit and Microsoft.Logging.

Now I get it! You want to repack the whole plugin to a single dll. The Package URL make sense in this case, and is better solution if that works by default with no extra steps.

I did a quick test with the https://github.com/gluck/il-repack/pull/390

And works really great, only need to change the hardcoded namespace to fix the theme change.

https://github.com/jeremytammik/RevitLookup/blob/6d6967b03d9268ab22505965387226e700b1c561/source/RevitLookup.UI/Appearance/ApplicationThemeManager.cs#L40C5-L41C1

```C#
//internal static string LibraryNamespace = "revitlookup.ui;";
internal static string LibraryNamespace { get; } = typeof(ApplicationThemeManager).Assembly.GetName().Name;
```

**Comment by Nice3point** [comment]
RevitLookup.UI can be left as a separate dll, like LookupEngine, they have no dependencies. I mean RevitLookup.UI.Framework, it contains Pack URIs like this: https://github.com/jeremytammik/RevitLookup/blob/dev/source/RevitLookup.UI.Framework/Markup/Menu/MenusDictionary.cs#L31

https://github.com/gluck/il-repack/pull/390 2 days ago, so it will be included in the next patch 🙂

**Comment by ricaun** [comment]
My idea was to not include the any UI dll in the repack. This new patch looks really promising. Let's wait for the release 🙂

**Comment by Nice3point** [comment]
If you notice any issues, let me know. The new version should work several times faster 🙂 Release in April

**Comment by Nice3point** [comment]
Is the problem only with repacking, or without it doesn't switch either?

**Comment by TorsionTools** [comment]
Ran into this the other day where lookup appears to be using a little bit older version than the latest that was being used in a project. Only happened in R24, but seems to be similar to this issue. If I shifted the load order, then the error message was thrown by the other add-in and not Lookup. 

See the end of this message for details on invoking

just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************

System.MissingMethodException: Method not found: 'Void Nice3point.Revit.Extensions.RibbonExtensions.SetImage(Autodesk.Revit.UI.RibbonButton, System.String)'.
   at RevitLookup.RibbonController.SetDefaultImage(RibbonButton button)
   at RevitLookup.RibbonController.CreatePanel(UIControlledApplication application, ISettingsService settingsService)
   at RevitLookup.Application.<OnStartup>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by Nice3point** [comment]
Beta is available: https://github.com/jeremytammik/RevitLookup/releases/tag/2026.0.0-preview.2.250222

**Comment by ricaun** [comment]
> Beta is available: https://github.com/jeremytammik/RevitLookup/releases/tag/2026.0.0-preview.2.250222

Did you use ILRepack?

**Comment by Nice3point** [comment]
@ricaun yes, ILRepack enabled for RevitLookup 2025 and older https://github.com/jeremytammik/RevitLookup/blob/dev/Directory.Packages.props#L52

**Comment by ricaun** [comment]
> [@ricaun](https://github.com/ricaun) yes, ILRepack enabled for RevitLookup 2025 and older https://github.com/jeremytammik/RevitLookup/blob/dev/Directory.Packages.props#L52

Nice.

This probably is irrelevant after the repack.
```
<!-- Revit 2025 fixed references -->
    <ItemGroup Condition="$(DefineConstants.Contains('NET8_0'))">
        <PackageVersion Update="Microsoft.Extensions.Hosting" Version="[8.0.1]"/>
        <PackageVersion Update="Serilog.Extensions.Hosting" Version="[8.0.0]"/>
        <PackageVersion Update="Microsoft.Extensions.Logging" Version="[8.0.1]"/>
    </ItemGroup>
```

Could be possible to release a .bundle.zip without any installation with the releases in the GitHub?

**Comment by Nice3point** [comment]
Why do you need a bundle, what is the purpose? @ricaun

**Comment by ricaun** [comment]
To install all Revit versions at the same time, is more convenient to install/update a simple folder. 
Yep, an issue/proposal makes sense.

**Comment by Nice3point** [comment]
I was thinking about WinGet, to install all versions from console

**Comment by russgreen** [comment]
2026.0.0-preview.2.250222 seems to be playing nicely with Revit 2025 and older versions of Revit when multiple plugins are installed (when previously I'd have some issues).

**Comment by ricaun** [comment]
Did you release with `ILRepack` for Revit 2026?

**Comment by Nice3point** [comment]
No, I'm using Autodesk's broken Context, I see you posted this morning on the forum that it still doesn't work. I'm going to leave it as is as a matter of principle for Autodesk to fix it @ricaun

**Comment by ricaun** [comment]
> No, I'm using Autodesk's broken Context, I see you posted this morning on the forum that it still doesn't work. I'm going to leave it as is as a matter of principle for Autodesk to fix it [@ricaun](https://github.com/ricaun)

Understand, I probably would use `ILRepack` in Revit 2026 as well just to make sure RevitLookup does not break any plugin or developing plugin. Autodesk probably has some weird reason to add that bypass inside the isolation context.

**Comment by Nice3point** [comment]
@ricaun I deleted that weird method.

![Image](https://github.com/user-attachments/assets/2258e5ed-57a6-41d5-8be9-59fe82369488)

And everything works as it should. No conflicts, no startup issues
![Image](https://github.com/user-attachments/assets/4a3c88c7-540e-480b-a868-46d6853cf7be)

They also added `FindMatchingAssemblyInFolder` method for `Assembly.GetExecutingAssembly().Location` for some reason. I.e. if it finds **Serilog** in the Revit folder, it will load it into your ALC, not from your plugin folder. Why Autodesk? Sounds logical for **RevitAPI.dll** and similar dependencies, but there is already an `IsRevitCoreAssembly` check. I totally don't understand the guy who leads the development of this feature
![Image](https://github.com/user-attachments/assets/3d4a6431-3ec9-462f-a58d-884ee732388c)

So, pathed dll:

[AddInLoader.zip](https://github.com/user-attachments/files/19657580/AddInLoader.zip)

**Comment by ricaun** [comment]
> [@ricaun](https://github.com/ricaun) I deleted that weird method.
> 
> So, pathed dll:
> 
> [AddInLoader.zip](https://github.com/user-attachments/files/19657580/AddInLoader.zip)

I did something similar and did work fine in Revit 2026, in the preview version the `AddInLoader` is a little different with some other weird stuff.
